# Top-level fields:
images: ['us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello']

# Options section:
options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  
  requestedVerifyOption: VERIFIED
  pool:
    name: "projects/bw-cbv2-sample-1/locations/us-central1/workerPools/fast-pool"

# Build steps:
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['compute', 'instances', 'create-with-container', 'my-vm-name', '--container-image', 'us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
