steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/cloud-run-tracker:$COMMIT_SHA', '.']  # Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/cloud-run-tracker:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - run
    - services
    - replace
    - cloud-run-tracker # Cloud Run service name
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/cloud-run-tracker:$COMMIT_SHA
    - --region=us-central1 # Region of Cloud Run service deployment
    - --project=$PROJECT_ID # Project of Cloud Run service deployment
    - --update-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-application-credentials
    - --set-secrets=GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-application-credentials
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/cloud-run-tracker:$COMMIT_SHA'  
options:
  logging: GCS_ONLY # or leave as the default if you also want Cloud Logging
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # This is the key chang
