# Top-level fields:
images: ['us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello']

# Options section:
options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  
  requestedVerifyOption: VERIFIED
  automapSubstitutions: true
  pool:
    name: "projects/bw-cbv2-sample-1/locations/us-central1/workerPools/fast-pool"

# Build steps:
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello', '.' ]
  id: A
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/bw-cbv2-sample-1/build-provenance/hello']
  id: B
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    echo "Hello $_USER"
  id: C
  waitFor: ['-']
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    echo "Your project ID is $PROJECT_ID"
  id: D
  waitFor: ['-']
    
substitutions:
  _USER: "Google Cloud"

