steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-tracker:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-run-tracker:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
    - run
    - services
    - replace
    - cloud-run-tracker
    - --image=gcr.io/$PROJECT_ID/cloud-run-tracker:$COMMIT_SHA
    - --region=YOUR_REGION
    - --project=$PROJECT_ID
images:
- 'gcr.io/$PROJECT_ID/cloud-run-tracker:$COMMIT_SHA'
